extends: .github

queue_rules:
  - name: default
    queue_conditions:
      - and: &CheckRuns
          - check-success=Test with Python 3.9
          - check-success=Test with Python 3.10
          - check-success=Test with Python 3.11
          - check-success=Test with Python 3.12
          - check-success = semgrep
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - "#review-requested=0"
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

  - name: lowprio
    queue_conditions:
      - and: *CheckRuns
      - "#commits=1"
      - author=dependabot[bot]
    merge_method: merge
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
    queue_branch_merge_method: fast-forward
pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - label!=manual merge
    actions:
      queue:

  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -merged
      - -closed
      - and: *CheckRuns
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs

merge_queue:
  max_parallel_checks: 5
priority_rules:
  - name: priority for queue `default`
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - "#review-requested=0"
    priority: 2250
