extends: .github

queue_rules:
  - name: default
    allow_inplace_checks: true
    queue_conditions:
      - and: &CheckRuns
          - check-success=test
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - "#review-requested=0"
    speculative_checks: 5
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

  - name: lowprio
    allow_inplace_checks: true
    queue_conditions:
      - and: *CheckRuns
      - "#commits=1"
      - author=dependabot[bot]
    merge_method: merge
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template: null
    queue_branch_merge_method: fast-forward
    disallow_checks_interruption_from_queues:
      - default

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - label!=manual merge
      - "check-success=Rule: Conventional Commit (post_check)"
    actions:
      queue:

  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -merged
      - -closed
      - and: *CheckRuns
      - "check-success=Rule: changelog requirements (post_check)"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs

  - name: changelog requirements
    conditions: []
    actions:
      post_check:
        title: |
          {% if check_succeeded %}
          Changelog requirements are present.
          {% else %}
          Changelog requirements are missing.
          {% endif %}
